name: Ganapathi Bank CI

on:
  push:
    branches:
      - main
      - develop

  pull_request:
    branches:
      - main
      - develop

jobs:
  build:

    runs-on: macos-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Select Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "4.0.6"
          bundler-cache: true

      - name: Install Gems
        run: bundle install

      - name: Run Fastlane CI
        run: bundle exec fastlane ci
